title = "Alvtime"
baseURL                          = "https://Alv-no.github.io/alvtime/"  # Your domain name. Must end with "/"
theme                            = "intro"
DefaultContentLanguage           = "no"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                       # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "hei@alv.no"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 100                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "Europe/Oslo"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "HH:mm"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = true
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    #[[params.social]]
    #    url   = "https://twitter.com/Alvnoas"
    #    icon  = "twitter" # icon name without the 'fa-'
    #    icon_pack = "fab"
    #[[params.social]]
    #    url   = "https://www.facebook.com/AlvNorge/"
    #    icon  = "facebook-f" # icon name without the 'fa-'
    #    icon_pack = "fab"
    #[[params.social]]
    #    url   = "https://www.linkedin.com/company/alvnorge/"
    #    icon  = "linkedin-in" # icon name without the 'fa-'
    #    icon_pack = "fab"
    #[[params.social]]
    #    url = "mailto:hei@alv.no"  # For a direct email link, use "mailto:test@example.org".
    #    icon = "paper-plane" # icon name without the 'fa-'
    #    icon_pack = "fas"
    #[[params.social]]
    #    url   = "https://instagram.com/alvnoas"
    #    icon  = "instagram" # icon name without the 'fa-'
    #    icon_pack = "fab"
    #[[params.social]]
    #    url   = "https://www.youtube.com/channel/UCLaJhfc1tFmHzP4usj1LKfA"
    #    icon  = "youtube" # icon name without the 'fa-'
    #    icon_pack = "fab"


# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
