version: '3.7'

services:
  dev:
    build: .
    container_name: alvtime-frontend
    tty: true
    image: alvtime-frontend
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
    command: sh
