name: Publish

on:
  push:
    branches:
      - master

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: publish
        run: |
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"

          echo "Deleting old publication"
          rm -rf site/public
          mkdir site/public
          git worktree prune
          rm -rf .git/worktrees/public/

          echo "Checking out gh-pages branch into public"
          git worktree add -B gh-pages site/public origin/gh-pages

          echo "Removing existing files"
          rm -rf site/public/*

          echo "Generating site"
          docker build -t alvtime-site . && docker run --rm -v $PWD/site:/usr/share/blog alvtime-site hugo

          echo "Updating gh-pages branch"
          cd site/public && git add --all && git commit -m "Publishing to gh-pages (publish_to_ghpages.sh)"

          echo "Pushing to github"
          git push --all
